services:
  fcp-sfd-frontend-internal:
    build:
      context: .
      target: development
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started
    environment:
      PORT: 3006
      NODE_ENV: development
      ALLOW_ERROR_VIEWS: ${ALLOW_ERROR_VIEWS:-false}
      DAL_ENDPOINT: ${DAL_ENDPOINT:-http://fcp-dal-api:3005/graphql}
      DAL_TOKEN_ENDPOINT: https://login.microsoftonline.com/${DAL_TENANT_ID}/oauth2/v2.0/token
      DAL_CLIENT_ID: ${DAL_CLIENT_ID}
      DAL_CLIENT_SECRET: ${DAL_CLIENT_SECRET}
      DAL_TENANT_ID: ${DAL_TENANT_ID}
      ENTRA_WELL_KNOWN_URL: https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0/.well-known/openid-configuration
      ENTRA_CLIENT_ID: ${ENTRA_CLIENT_ID}
      ENTRA_CLIENT_SECRET: ${ENTRA_CLIENT_SECRET}
      ENTRA_REDIRECT_URL: http://localhost:3006/auth/sign-in-oidc
      ENTRA_SIGN_OUT_REDIRECT_URL: http://localhost:3006/auth/sign-out-oidc

  upstream-mock:
    image: defradigital/fcp-dal-upstream-mock:0.79.0
    environment:
      MOCK_LOG_LEVEL: info
      MOCK_SERVER_COLLECTION: all
      NODE_ENV: development
      PORT: 3100
      KIT_EXT_PERSON_ID_OVERRIDE: 3000000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3100/health']
      interval: 3s
      timeout: 2s
      retries: 5

  fcp-dal-api:
    image: defradigital/fcp-dal-api:2.2.1
    depends_on:
      upstream-mock:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      ALL_SCHEMA_ON: true
      LOG_LEVEL: info
      NODE_ENV: development
      PORT: 3005
      ENVIRONMENT: dev
      DISABLE_AUTH: true
      HITACHI_DISABLE_AUTH: true
      DISABLE_PROXY: true
      GRAPHQL_DASHBOARD_ENABLED: true
      ADMIN_AD_GROUP_ID: unused
      KITS_INTERNAL_GATEWAY_URL: http://upstream-mock:3100/extapi/
      KITS_EXTERNAL_GATEWAY_URL: http://upstream-mock:3100/extapi/
      KIT_EXT_PERSON_ID_OVERRIDE: 3000000
      KITS_GATEWAY_TIMEOUT_MS: 3000
      KITS_DISABLE_MTLS: true
      HITACHI_GATEWAY_URL: http://upstream-mock:3100/api/
      HITACHI_TIMEOUT_MS: 3000
      MONGO_URI: mongodb://mongo:27017
      DAL_REQUEST_TIMEOUT_MS: 3000

  redis:
    image: redis:7.2.3-alpine3.18

  mongo:
    image: mongo:8.2
