services:
  fcp-sfd-frontend-internal:
    build:
      context: .
      target: development
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7.2.3-alpine3.18
    restart: always
