services:
  fcp-sfd-frontend-internal:
    ports:
      - '3006:3006'
      - '9262:9229'
    networks:
      - fcp-sfd
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  kits-mock:
    ports:
      - '3100:3100'
    networks:
      - fcp-sfd

  fcp-dal-api:
    ports: 
      - 3005:3005
    networks:
      - fcp-sfd

  redis:
    ports:
      - '6379:6379'
    networks:
      - fcp-sfd

networks:
  fcp-sfd:
    driver: bridge
