services:
  fcp-sfd-frontend-internal:
    build:
      target: development
    image: fcp-sfd-frontend-internal-development
    container_name: fcp-sfd-frontend-internal-test
    command: npm run test
    env_file:
      - path: .env
        required: false
    environment:
      ALLOW_ERROR_VIEWS: false
      DAL_ENDPOINT: http://fcp-dal-api:3005/graphql
      DAL_CONNECTION: false
      ENTRA_WELL_KNOWN_URL: https://accounts.test.com/.well-known/openid-configuration
      ENTRA_CLIENT_ID: test-client-id
      ENTRA_CLIENT_SECRET: test-client-secret
    depends_on:
      fcp-dal-api:
        condition: service_started
      kits-mock:
        condition: service_started
    volumes:
      - ./src/:/home/node/src
      - ./test/:/home/node/test
      - ./package.json:/home/node/package.json
      - ./coverage:/home/node/coverage
